### ISSUE TITLE
ReferenceError: File is not defined in ofd.js

### ISSUE THREAD

**Issue by annaLin2018** [DLTech21/ofd.js#23]
Using command:
install: npm install ofd.js --save-dev
import: var ofdjs = require('ofd.js');
when node xxx.js the following error is thrown.
ReferenceError: File is not defined
    at Module.C (D:\spring\frontend\demo\nodejs12\node_modules\ofd.js\lib\ofd.umd.min.js:67:179480)
    at displayOfdDiv (D:\spring\frontend\demo\nodejs12\app.js:28:11)
    at D:\spring\frontend\demo\nodejs12\app.js:92:4
    at Layer.handle [as handle_request] (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\layer.js:95:5)
    at D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\index.js:335:12)
    at next (D:\spring\frontend\demo\nodejs12\node_modules\express\lib\router\index.js:275:10)

**Comment by DLTech21** [comment]
不会用不了的，看看是不是环境问题

**Comment by annaLin2018** [comment]
could you give one example how to use it?
